export { default as HeroSection } from './HeroSection'
export { default as AcceptMethods } from './AcceptMethods'
export { default as DeveloperIntegration } from './DeveloperIntegration'
export { default as EmpoweringSuccess } from './EmpoweringSuccess'
export { default as FeesComparison } from './FeesComparison'
export { default as PerfectFor } from './PerfectFor'
export { default as Plugins } from './Plugins'
export { default as FAQSection } from './FAQSection'
