import ApiEndpoint from '@/components/docs/ApiEndpoint'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Pay-In API Documentation | RupeeFlow',
  description: 'Complete Pay-In API documentation for accepting UPI payments. Learn how to create payment requests, check transaction status, and handle webhooks.',
  keywords: ['Pay-In API', 'UPI payment API', 'accept payments', 'payment gateway', 'UPI collect', 'payment integration'],
}

export default function PayinDocsPage() {
  return (
    <div>
      {/* Header */}
      <div className="mb-12">
        <h1 className="text-5xl fontheading2 text-gradient-teal-emerald mb-4">
          Pay-In API
        </h1>
        <p className="text-xl text-gray-300 fontbody mb-6">
          Accept payments from customers using UPI. Create payment requests, track transaction status, and receive real-time webhook notifications.
        </p>

        {/* Version Badge */}
        <div className="inline-flex items-center gap-2 px-4 py-2 bg-teal-500/20 border border-teal-500/30 rounded-lg">
          <span className="text-teal-400 fontbody font-semibold">Version 1.0</span>
        </div>
      </div>

      {/* Divider */}
      <div className="border-t border-gray-800 mb-12"></div>

      {/* Endpoint 1: Initiate Payin Transaction */}
      <ApiEndpoint
        method="POST"
        endpoint="{{base_url}}/api/v1/payments/payin/create"
        title="Initiate Payin Transaction"
        description="Create a UPI payment request. Once you receive a successful response, the customer will receive a payment request on their UPI app."
        headers={[
          { name: 'Content-Type', value: 'application/json' },
          { name: 'Authorization', value: 'Basic <Base64(ClientID:ClientSecret)>', description: 'Basic Auth using Client ID and Secret' },
        ]}
        requestBody={`{
  "amount": 100,
  "name": "Test",
  "email": "test@rupeeflow.in",
  "mobile": "9999900000",
  "vpa": "9999900000@ybl"
}`}
        responseBody={`{
  "statusCode": 201,
  "message": "Data Received",
  "success": true,
  "data": {
    "orderId": "test_12345890",
    "message": "Payment Request Sent Successfully"
  }
}`}
        curlExample={`curl --location '{{base_url}}/api/v1/payments/payin/create' \\
--header 'Content-Type: application/json' \\
--header 'Authorization: Basic a2V5XzAxa2V5XzAxSkXXXXXXXXXXXX2V5XzAxSk' \\
--data-raw '{
  "amount": 100,
  "name": "Test",
  "email": "test@rupeeflow.in",
  "mobile": "9999900000",
  "vpa": "9999900000@ybl"
}'`}
        notes={[
          'Order ID: A unique order ID is generated by the bank and returned in the response',
          'Minimum Amount: 100 (decimal not mandatory, e.g., 100.00)',
          'Name: Customer&apos;s full name',
          'Email: Customer&apos;s email address (required for notifications)',
          'Mobile: Customer&apos;s 10-digit mobile number',
          'VPA: Customer&apos;s UPI ID (e.g., 9876543210@ybl, username@paytm)',
        ]}
      />

      {/* Endpoint 2: Check Payin Transaction Status */}
      <ApiEndpoint
        method="POST"
        endpoint="{{base_url}}/api/v1/payments/payin/status"
        title="Check Payin Transaction Status"
        description="Retrieve the current status of a pay-in transaction using the order ID."
        headers={[
          { name: 'Content-Type', value: 'application/json' },
          { name: 'Authorization', value: 'Basic <Base64(ClientID:ClientSecret)>' },
        ]}
        requestBody={`{
  "orderId": "test_12345890"
}`}
        responseBody={`{
  "statusCode": 200,
  "message": "Data Received",
  "success": true,
  "data": {
    "orderId": "test_12345890",
    "status": "SUCCESS",
    "txnRefId": "094320545671"
  }
}`}
        curlExample={`curl --location '{{base_url}}/api/v1/payments/payin/status' \\
--header 'Content-Type: application/json' \\
--header 'Authorization: Basic a2V5XzAxa2V5XzAxSkXXXXXXXXXXXX2V5XzAxSk' \\
--data-raw '{
  "orderId": "test_12345890"
}'`}
        notes={[
          'Status can be: SUCCESS, PENDING, or FAILED',
          'txnRefId: Bank transaction reference number (UTR)',
          'Poll this endpoint to check transaction status',
          'Recommended polling interval: 5-10 seconds',
        ]}
      />

      {/* Endpoint 3: Payin Webhook Response */}
      <div className="mb-12">
        <div className="bg-gradient-to-br from-purple-500/10 to-blue-500/10 border border-purple-500/30 rounded-xl p-6 mb-6">
          <h2 className="text-3xl fontheading text-purple-400 mb-3">Payin Webhook Response</h2>
          <p className="text-gray-300 fontbody2 mb-4">
            Configure your webhook URL in the dashboard to receive real-time payment status updates. We&apos;ll send a POST request to your endpoint whenever the payment status changes.
          </p>
          <div className="bg-gray-950 border border-purple-500/20 rounded-lg p-4">
            <p className="text-sm text-gray-400 fontbody2 mb-2">Configure in Dashboard:</p>
            <code className="text-purple-400 text-sm">Settings → Webhooks → Add Webhook URL</code>
          </div>
        </div>

        <h3 className="text-xl fontheading text-emerald-400 mb-3">Webhook Payload</h3>
        <pre className="bg-gray-950 border border-gray-800 rounded-lg p-4 overflow-x-auto mb-4">
          <code className="text-sm text-gray-300 font-mono">{`{
  "orderId": "test_12345890",
  "status": "SUCCESS",
  "amount": 100,
  "txnRefId": "094320545671"
}`}</code>
        </pre>

        <div className="bg-gradient-to-br from-teal-500/10 to-emerald-500/10 border border-teal-500/30 rounded-lg p-4">
          <h4 className="text-lg fontheading text-teal-400 mb-2">📝 Webhook Notes</h4>
          <ul className="space-y-2">
            <li className="text-gray-300 fontbody2 text-sm flex items-start gap-2">
              <span className="text-teal-500 mt-1">•</span>
              <span>Webhook is sent whenever payment status changes (SUCCESS, FAILED, PENDING)</span>
            </li>
            <li className="text-gray-300 fontbody2 text-sm flex items-start gap-2">
              <span className="text-teal-500 mt-1">•</span>
              <span>Your webhook endpoint must return HTTP 200 status code</span>
            </li>
            <li className="text-gray-300 fontbody2 text-sm flex items-start gap-2">
              <span className="text-teal-500 mt-1">•</span>
              <span>We&apos;ll retry failed webhooks up to 3 times with exponential backoff</span>
            </li>
            <li className="text-gray-300 fontbody2 text-sm flex items-start gap-2">
              <span className="text-teal-500 mt-1">•</span>
              <span>txnRefId contains the bank&apos;s UTR (Unique Transaction Reference)</span>
            </li>
          </ul>
        </div>
      </div>

      {/* Status Codes */}
      <div className="mb-12">
        <h2 className="text-3xl fontheading text-white mb-6">Status Codes</h2>
        <div className="bg-gray-900/50 border border-gray-800 rounded-lg overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-950">
              <tr>
                <th className="px-6 py-3 text-left text-sm fontheading text-emerald-400">Status</th>
                <th className="px-6 py-3 text-left text-sm fontheading text-emerald-400">Description</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-800">
              <tr>
                <td className="px-6 py-4 text-sm">
                  <code className="text-emerald-400 fontbody">SUCCESS</code>
                </td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">
                  Payment completed successfully. Funds credited to your account.
                </td>
              </tr>
              <tr>
                <td className="px-6 py-4 text-sm">
                  <code className="text-yellow-400 fontbody">PENDING</code>
                </td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">
                  Payment initiated but not yet completed. Check again after a few seconds.
                </td>
              </tr>
              <tr>
                <td className="px-6 py-4 text-sm">
                  <code className="text-red-400 fontbody">FAILED</code>
                </td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">
                  Payment failed. Customer needs to retry the payment.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* Error Codes */}
      <div className="mb-12">
        <h2 className="text-3xl fontheading text-white mb-6">Common Error Codes</h2>
        <div className="bg-gray-900/50 border border-gray-800 rounded-lg overflow-hidden">
          <table className="w-full">
            <thead className="bg-gray-950">
              <tr>
                <th className="px-6 py-3 text-left text-sm fontheading text-emerald-400">Code</th>
                <th className="px-6 py-3 text-left text-sm fontheading text-emerald-400">Message</th>
                <th className="px-6 py-3 text-left text-sm fontheading text-emerald-400">Solution</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-800">
              <tr>
                <td className="px-6 py-4 text-sm">
                  <code className="text-red-400 fontbody">401</code>
                </td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">Unauthorized</td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">Check your Client ID and Secret Key</td>
              </tr>
              <tr>
                <td className="px-6 py-4 text-sm">
                  <code className="text-red-400 fontbody">403</code>
                </td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">IP Not Whitelisted</td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">Whitelist your IP in Developer Section</td>
              </tr>
              <tr>
                <td className="px-6 py-4 text-sm">
                  <code className="text-red-400 fontbody">400</code>
                </td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">Bad Request</td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">Check request body format and required fields</td>
              </tr>
              <tr>
                <td className="px-6 py-4 text-sm">
                  <code className="text-red-400 fontbody">500</code>
                </td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">Internal Server Error</td>
                <td className="px-6 py-4 text-sm text-gray-300 fontbody2">Contact support if issue persists</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
